---
# tasks file for zabbix
- name: Скачивание пакета репозитория Zabbix
  get_url:
    url: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release_latest_7.2+ubuntu22.04_all.deb"

- name: Установка пакета репозитория Zabbix
  command: dpkg -i /tmp/zabbix-release_latest_7.2+ubuntu22.04_all.deb

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка Zabbix
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - python3-pip
      - zabbix-sql-scripts
      - php8.1-pgsql
      - postgresql
      - postgresql-client
    state: present
    update_cache: yes

- name: Установка библиотеки psycopg2-binary
  pip:
    name: psycopg2-binary
    state: present

- name: Настройка конфигурации Zabbix Server
  template:
    src: "zabbix_server.conf.j2"
    dest: "/etc/zabbix/zabbix_server.conf"
  notify:
    - Restart zabbix-server

- name: Настройка конфигурации Zabbix Frontend
  template:
    src: "zabbix.conf.php.j2"
    dest: "/usr/share/zabbix/ui/conf/zabbix.conf.php"

- name: Получить IP-адрес Zabbix сервера
  set_fact:
    zabbix_server_ip: "{{ ansible_host }}"

- name: Настройка Zabbix Agent на хостах
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"
  notify:
    - Restart zabbix-agent

- name: Создать файл-флаг завершения установки
  file:
    path: "/usr/share/zabbix/ui/conf/installed"
    state: touch

- name: Настройка NGINX для Zabbix
  copy:
    content: |
      server {
          listen          80;
          server_name     {{ ansible_host }};

          root            /usr/share/zabbix/ui;

          index           index.php;

          location / {
              try_files $uri $uri/ /index.php;
          }

          location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
      }
    dest: /etc/nginx/sites-available/zabbix
  notify:
    - Reload nginx

- name: Настройка параметров PHP
  lineinfile:
    path: "/etc/php/8.1/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^post_max_size =', line: 'post_max_size = 16M' }
    - { regexp: '^max_execution_time =', line: 'max_execution_time = 300' }
    - { regexp: '^max_input_time =', line: 'max_input_time = 300' }

- name: Перезагрузка PHP-FPM
  service:
    name: php8.1-fpm
    state: restarted

- name: Активировать конфигурацию NGINX
  file:
    src: /etc/nginx/sites-available/zabbix
    dest: /etc/nginx/sites-enabled/zabbix
    state: link
  notify:
    - Reload nginx

- name: Удалить дефолтную конфигурацию NGINX
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload nginx