---
# tasks file for zabbix
- name: Добавление ключа для репозитория Zabbix
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present    

- name: Добавление репозитория Zabbix
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu jammy main"
    state: present

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка Zabbix
  apt:
    name:
      - zabbix-server-pgsql
      - postgresql
      - postgresql-client
    state: present
    update_cache: yes

- name: Настройка конфигурации Zabbix Server
  template:
    src: "zabbix_server.conf.j2"
    dest: "/etc/zabbix/zabbix_server.conf"
  notify:
    - Restart zabbix-server

- name: Получить IP-адрес Zabbix сервера
  set_fact:
    zabbix_server_ip: "{{ hostvars['zabbix']['ansible_default_ipv4']['address'] }}"

- name: Настройка Zabbix Agent на хостах
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"
  notify:
    - Restart zabbix-agent

- name: Включение и запуск Zabbix Server
  service:
    name: zabbix-server
    state: started
    enabled: yes