---
# tasks file for zabbix
- name: Скачивание пакета репозитория Zabbix
  get_url:
    url: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release_latest_7.2+ubuntu22.04_all.deb"

- name: Установка пакета репозитория Zabbix
  command: dpkg -i /tmp/zabbix-release_latest_7.2+ubuntu22.04_all.deb

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка Zabbix
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - php8.1-pgsql
      - postgresql
      - postgresql-client
    state: present
    update_cache: yes

- name: Настройка конфигурации Zabbix Server
  template:
    src: "zabbix_server.conf.j2"
    dest: "/etc/zabbix/zabbix_server.conf"
  notify:
    - Restart zabbix-server

- name: Получить IP-адрес Zabbix сервера
  set_fact:
    zabbix_server_ip: "{{ ansible_host }}"

- name: Настройка Zabbix Agent на хостах
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"
  notify:
    - Restart zabbix-agent