---
# handlers file for postgres
- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart patroni
  service:
    name: patroni
    state: restarted    