---
# tasks file for postgres
- name: Установка PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Установка зависимостей для Patroni
  apt:
    name:
      - python3-pip
      - python3-dev
      - libpq-dev
    state: present

- name: Установка Patroni
  pip:
    name: patroni
    state: present
