---
# tasks file for default
- name: Установка пакетов
  apt:
    name:
      - net-tools
      - rsync
      - rsyslog
      - curl
      - wget
      - python3-pip
      - zabbix-agent
    state: present
    update_cache: yes

- name: попытка исправить ошибки запуска агента
  file:
    path: /etc/zabbix/zabbix_agentd.d
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Настройка конфигурации Zabbix Agent
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: zabbix
    group: zabbix
    mode: '0644'

  vars:
    zabbix_server_ip: "{{ hostvars['zabbix'].ansible_host | default('') }}"

- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted