---
# tasks file for default
- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка пакетов
  apt:
    name:
      - net-tools
      - zabbix-agent
      - rsync
      - rsyslog
      - mc
      - curl
      - wget
      - apt-transport-https
      - ca-certificates
      - python3-pip
    state: present
    update_cache: yes

- name: Установка библиотеки psycopg2-binary
  pip:
    name: "{{ psycopg2_package }}"
    state: present

- name: Настройка конфигурации Zabbix Agent
  template:
    src: "zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
  vars:
    zabbix_server_ip: "{{ hostvars['zabbix'].ansible_host | default('') }}"
  notify:
    - Restart zabbix-agent  # Уведомление для перезапуска службы