---
# tasks file for nginx
- name: Установка NGINX
  apt:
    name: "nginx"
    state: present
    update_cache: yes

- name: Проверка, что пользователь nginx существует
  user:
    name: nginx
    state: present

- name: Настройка конфигурации nginx для балансировки нагрузки
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx