---
# tasks file for nginx
- name: Установка пакетов
  apt:
    name:
      - php8.1-fpm
      - php8.1-cli
      - python3-pip
      - php8.1-mysql
      - php8.1-curl
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-opcache
    state: present
    update_cache: yes 

- name: Установка библиотеки psycopg2-binary
  pip:
    name: psycopg2-binary
    state: present

- name: Попытка установки NGINX с повторами
  block:
    - name: Выполнить установку NGINX
      apt:
        name: "nginx"
        state: present
        update_cache: yes
      register: apt_result
      retries: 3
      delay: 30
      until: apt_result is succeeded
  rescue:
    - name: Вывод отладки при ошибке установки NGINX
      debug:
        msg: "Не удалось установить NGINX после нескольких попыток. Проверьте блокировки apt и состояние системы."

- name: Проверка, что пользователь nginx существует
  user:
    name: nginx
    state: present

- name: Настройка конфигурации nginx для балансировки нагрузки
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  
- name: Настройка default
  template:
    src: "default.conf.j2"
    dest: "/etc/nginx/sites-available/default"
  notify:
    - Restart nginx