---
# defaults file for postgres
max_connections: 200
shared_buffers: 256MB
max_wal_senders: 10
hot_standby: "on"
patroni_version: "2.0.0"
postgresql_version: "14"
postgres_host: "{{ ansible_host }}"
postgres_user: "postgres"  
postgres_password: "Kve6@Xa" 
wikiuser_password: "balamut666"
zabbix_password: "i7def"
etcd_version: "v3.5.0"
patroni_password: "1234"
etcd_host1: "{{ hostvars['psql1']['ansible_host'] }}"
etcd_host2: "{{ hostvars['psql2']['ansible_host'] }}"
patroni_user: "postgres"
patroni_data_dir: "/var/lib/postgresql/14/main"
patroni_conf_dir: "/etc/patroni"