---
# defaults file for postgres
max_connections: 200
shared_buffers: 256MB
max_wal_senders: 10
hot_standby: "on"
patroni_version: "2.0.0"
postgresql_version: "14"
patroni_cluster_name: "pg_cluster"
patroni_data_dir: "/var/lib/postgresql/data"
patroni_bin_dir: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
patroni_config_file: "/etc/patroni/patroni.yml"
patroni_etcd_host: "http://{{ ansible_host }}"
patroni_restapi_listen: "0.0.0.0:8008"
patroni_postgresql_listen: "0.0.0.0:5432"
patroni_postgresql_connect_address: "127.0.0.1:5432"
patroni_private_ip: "{{ ansible_host }}"
patroni_node_name: "{{ ansible_hostname }}"
postgres_host: "{{ ansible_host }}"
postgres_user: "postgres"  
postgres_password: "Kve6@Xa" 
wikiuser_password: "balamut666"
zabbix_password: "i7def"