- name: Настройка MediaWiki
  hosts: mediawiki

  vars:
    postgres_host: "{{ hostvars['psql1'].ansible_host }}"
    postgres_user: "wikiuser"
    postgres_password: "balamut666"

  tasks:
    - name: Применение роли для MediaWiki
      include_role:
        name: mediawiki

- name: Настройка Nginx
  hosts: nginx

  vars:
    mediawiki1_ip: "{{ hostvars['mw1'].ansible_host }}"
    mediawiki2_ip: "{{ hostvars['mw2'].ansible_host }}"

  tasks:
    - name: Применение роли для Nginx
      include_role:
        name: nginx

- name: Настройка Zabbix
  hosts: zabbix

  vars:
    postgres_host: "{{ hostvars['psql1'].ansible_host }}"
    postgres_user: "zabbix"
    postgres_password: "i7def"

  tasks:
    - name: Применение роли для zabbix
      include_role:
        name: zabbix

- name: Настройка всех сервисов+zabbixagent
  hosts: all

  tasks:
    - name: Применение роли для установки общих пакетов
      include_role:
        name: default