---
# tasks file for minio
- name: Убедиться, что необходимые пакеты для добавления репозитория установлены
  apt:
    name:
      - apt-transport-https
      - wget
    state: present
    update_cache: yes

- name: Установка MinIO
  apt:
    name: "minio"
    state: present
    update_cache: yes
  
- name: Скачать MinIO бинарный файл
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: "/usr/local/bin/minio"
    mode: '0755'

- name: Создать пользователя и группу для MinIO
  user:
    name: minio
    state: present
    system: yes

- name: Создать директорию для данных MinIO
  file:
    path: /data/minio
    state: directory
    owner: minio
    group: minio
    mode: '0755'
